### ISSUE TITLE
Update to include hal-flash.ads from Ada Drivers Library

### ISSUE THREAD

**Issue by thatcomputerguy0101** [Fabien-Chouteau/hal#1]
Hi, it would be useful if you could update this mirror to include [hal-flash.ads](https://github.com/AdaCore/Ada_Drivers_Library/blob/master/hal/src/hal-flash.ads) from the Ada Drivers Library repository. Thanks in advance.

**Comment by Fabien-Chouteau** [comment]
Hi @thatcomputerguy0101, the PR is in: https://github.com/alire-project/alire-index/pull/1025
